language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-25.*
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25.*
    - sys-img-armeabi-v7a-android-25.*
before_script:
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./android-licenses/* "$ANDROID_HOME/licenses/"
before_install:
 - chmod +x gradlew
script:
    - ./gradlew build check